// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 07.06.2026, 16:15:32
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/andre/jsProjects/nuxt-freedom-astana/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/andre/jsProjects/nuxt-freedom-astana/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/andre/jsProjects/nuxt-freedom-astana/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/andre/jsProjects/nuxt-freedom-astana/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/andre/jsProjects/nuxt-freedom-astana/plugins/**/*.{js,ts,mjs}","C:/Users/andre/jsProjects/nuxt-freedom-astana/composables/**/*.{js,ts,mjs}","C:/Users/andre/jsProjects/nuxt-freedom-astana/utils/**/*.{js,ts,mjs}","C:/Users/andre/jsProjects/nuxt-freedom-astana/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/andre/jsProjects/nuxt-freedom-astana/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/andre/jsProjects/nuxt-freedom-astana/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/andre/jsProjects/nuxt-freedom-astana/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;